import type { AIAnalysis, Keyword, ThreadsPost } from '@/lib/types';

export const demoPosts: ThreadsPost[] = [
  {
    id: 'demo-low-bridge-glasses',
    author: 'Mina Le',
    authorHandle: '@minafinds',
    content: 'People with low nose bridges always struggle wearing glasses. Every frame slowly slides down like it has somewhere else to be.',
    likes: 18400,
    replies: 912,
    reposts: 3300,
    timestamp: new Date(Date.now() - 1000 * 60 * 42).toISOString(),
    imageUrls: [],
    url: 'https://www.threads.net/@minafinds/post/demo-low-bridge-glasses',
    source: 'trending',
    keyword: 'glasses',
    fetchedAt: new Date().toISOString(),
    trendingScore: 91,
    affiliateFitScore: 92,
    opportunityScore: 92,
    velocityScore: 24,
    engagementGrowthPercent: 38,
    emotionalCategory: 'insecurity'
  },
  {
    id: 'demo-office-neck',
    author: 'Jon Park',
    authorHandle: '@deskday',
    content: 'No one tells you that office work is mostly neck pain, dry eyes, and pretending the chair is comfortable.',
    likes: 9800,
    replies: 680,
    reposts: 2100,
    timestamp: new Date(Date.now() - 1000 * 60 * 78).toISOString(),
    imageUrls: [],
    url: 'https://www.threads.net/@deskday/post/demo-office-neck',
    source: 'keyword',
    keyword: 'office problems',
    fetchedAt: new Date().toISOString(),
    trendingScore: 84,
    affiliateFitScore: 79,
    opportunityScore: 80,
    velocityScore: 18,
    engagementGrowthPercent: 22,
    emotionalCategory: 'frustration'
  },
  {
    id: 'demo-skincare',
    author: 'Ava Cho',
    authorHandle: '@skinnotes',
    content: 'The worst part about trying new skincare is not knowing whether it is purging, irritation, or your face filing a complaint.',
    likes: 7200,
    replies: 534,
    reposts: 1450,
    timestamp: new Date(Date.now() - 1000 * 60 * 130).toISOString(),
    imageUrls: [],
    url: 'https://www.threads.net/@skinnotes/post/demo-skincare',
    source: 'keyword',
    keyword: 'skincare',
    fetchedAt: new Date().toISOString(),
    trendingScore: 78,
    affiliateFitScore: 62,
    opportunityScore: 66,
    velocityScore: 10,
    engagementGrowthPercent: 12,
    emotionalCategory: 'anxiety'
  }
];

export const demoAnalysis: Record<string, AIAnalysis> = {
  'demo-low-bridge-glasses': {
    postId: 'demo-low-bridge-glasses',
    verdict: 'make_now',
    confidenceScore: 94,
    emotion: 'insecurity',
    painPoint: 'glasses slipping and making the wearer feel self-conscious',
    buyingIntent: 'high',
    affiliateCategories: ['eyewear accessories', 'beauty comfort', 'daily carry'],
    affiliateProducts: ['anti-slip glasses hooks', 'adhesive nose pads', 'lightweight acetate frames'],
    contentAngle: 'relatable struggle with a simple fix',
    whyViral: 'The post names a specific physical frustration that many people recognize but rarely see described directly.',
    hooks: ['Low nose bridge? Your glasses are not the problem.', 'This tiny glasses fix saves so much adjusting.'],
    ctas: ['People with low nose bridges need this.', 'Try this before buying another frame.'],
    relatabilityScore: 92,
    controversyScore: 18,
    affiliateFitScore: 96,
    personas: ['người đeo kính sống mũi thấp', 'người thường vận động hoặc đổ mồ hôi'],
    situations: ['kính tụt khi cúi xuống', 'kính trượt khi vận động'],
    demoAngle: 'Quay cận cảnh kính tụt trước khi gắn móc silicone và giữ chắc sau khi gắn.',
    contentFormat: 'hook nỗi đau -> tình huống relatable -> demo giải pháp nhỏ -> CTA',
    solutionScript: 'Ê nhưng có cách xử lý gọn lắm nha! Thử gắn móc silicone chống tụt kính vào đuôi gọng, nhỏ xíu mà đeo đỡ phải đẩy kính liên tục. Ai hay vận động hoặc đổ mồ hôi thì thử xem sao nhé.',
    productSearchKeywords: ['móc silicone chống tụt kính', 'đệm mũi kính silicone'],
    scriptOutline: ['0:00-0:03: Kính tự tụt khi cúi xuống', '0:03-0:08: Gắn móc silicone', '0:08-0:13: Demo vận động và CTA'],
    createdAt: new Date().toISOString()
  },
  'demo-office-neck': {
    postId: 'demo-office-neck',
    verdict: 'make_now',
    confidenceScore: 82,
    emotion: 'fatigue',
    painPoint: 'desk posture discomfort and dry eyes during long workdays',
    buyingIntent: 'medium',
    affiliateCategories: ['ergonomics', 'office wellness', 'productivity'],
    affiliateProducts: ['laptop stand', 'memory foam seat cushion', 'blue light desk lamp'],
    contentAngle: 'workday survival kit',
    whyViral: 'It compresses several common office annoyances into one punchy observation.',
    hooks: ['Your desk setup is why your neck hurts.', 'Three quiet upgrades for anyone sitting all day.'],
    ctas: ['Fix the setup before blaming your schedule.', 'Start with the one desk item you use most.'],
    relatabilityScore: 88,
    controversyScore: 12,
    affiliateFitScore: 82,
    personas: ['dân văn phòng ngồi máy tính lâu'],
    situations: ['đau cổ cuối ngày', 'mỏi mắt khi làm việc'],
    demoAngle: 'So sánh tư thế trước và sau khi nâng laptop.',
    contentFormat: 'hook nỗi đau -> setup sai -> demo thay đổi -> CTA',
    solutionScript: 'Khoan mua thêm đồ linh tinh nha, thử kê laptop lên đúng tầm mắt trước đã! Một chiếc giá đỡ laptop gọn nhẹ có thể giúp setup nhìn đỡ mỏi hơn hẳn. Dân ngồi máy tính lâu nên thử xem sao.',
    productSearchKeywords: ['giá đỡ laptop', 'đệm ghế văn phòng memory foam'],
    scriptOutline: ['0:00-0:03: Tư thế ngồi gây mỏi cổ', '0:03-0:09: Demo setup trước và sau', '0:09-0:14: CTA xem sản phẩm'],
    createdAt: new Date().toISOString()
  }
};

export const defaultKeywords: Keyword[] = [
  { id: 'kw-vi-glasses', phrase: 'kính tụt', enabled: true, cadenceMinutes: 90 },
  { id: 'kw-vi-oily-skin', phrase: 'da dầu', enabled: true, cadenceMinutes: 120 },
  { id: 'kw-vi-hair-loss', phrase: 'tóc rụng', enabled: true, cadenceMinutes: 120 },
  { id: 'kw-vi-office-pain', phrase: 'đau lưng văn phòng', enabled: true, cadenceMinutes: 120 },
  { id: 'kw-vi-sleep', phrase: 'mất ngủ', enabled: true, cadenceMinutes: 180 },
  { id: 'kw-vi-beauty', phrase: 'tự ti ngoại hình', enabled: false, cadenceMinutes: 180 },
  { id: 'kw-vi-productivity', phrase: 'mẹo tiện lợi', enabled: false, cadenceMinutes: 180 }
];
